{"ast":null,"code":"import axios from \"axios\";\nimport { toast } from \"react-toastify\";\n\nconst successCallBack = success => {\n  toast.error(success.data.message);\n};\n\nconst errorCallBack = error => {\n  const expectedError = error.response && error.response.status >= 404 && error.response.status < 500;\n\n  if (!expectedError) {\n    console.log(\"logging the error\", error);\n    toast.error(\"an unexpected error occured\");\n  }\n\n  return Promise.reject(error);\n}; //intercept errors while communicating with backend server\n\n\naxios.interceptors.response.use(successCallBack, errorCallBack);\nexport default {\n  get: axios.get,\n  post: axios.post,\n  put: axios.put,\n  delete: axios.delete\n};","map":{"version":3,"sources":["/Users/prashantkansal/Desktop/techgropse/digiTender/digiTenderFrontend/src/services/httpService.js"],"names":["axios","toast","successCallBack","success","error","data","message","errorCallBack","expectedError","response","status","console","log","Promise","reject","interceptors","use","get","post","put","delete"],"mappings":"AAAA,OAAOA,KAAP,MAAkB,OAAlB;AACA,SAASC,KAAT,QAAsB,gBAAtB;;AACA,MAAMC,eAAe,GAAIC,OAAD,IAAa;AACnCF,EAAAA,KAAK,CAACG,KAAN,CAAYD,OAAO,CAACE,IAAR,CAAaC,OAAzB;AACD,CAFD;;AAIA,MAAMC,aAAa,GAAIH,KAAD,IAAW;AAC/B,QAAMI,aAAa,GACjBJ,KAAK,CAACK,QAAN,IACAL,KAAK,CAACK,QAAN,CAAeC,MAAf,IAAyB,GADzB,IAEAN,KAAK,CAACK,QAAN,CAAeC,MAAf,GAAwB,GAH1B;;AAIA,MAAI,CAACF,aAAL,EAAoB;AAClBG,IAAAA,OAAO,CAACC,GAAR,CAAY,mBAAZ,EAAiCR,KAAjC;AACAH,IAAAA,KAAK,CAACG,KAAN,CAAY,6BAAZ;AACD;;AACD,SAAOS,OAAO,CAACC,MAAR,CAAeV,KAAf,CAAP;AACD,CAVD,C,CAYA;;;AACAJ,KAAK,CAACe,YAAN,CAAmBN,QAAnB,CAA4BO,GAA5B,CAAgCd,eAAhC,EAAiDK,aAAjD;AAEA,eAAe;AACbU,EAAAA,GAAG,EAAEjB,KAAK,CAACiB,GADE;AAEbC,EAAAA,IAAI,EAAElB,KAAK,CAACkB,IAFC;AAGbC,EAAAA,GAAG,EAAEnB,KAAK,CAACmB,GAHE;AAIbC,EAAAA,MAAM,EAAEpB,KAAK,CAACoB;AAJD,CAAf","sourcesContent":["import axios from \"axios\";\nimport { toast } from \"react-toastify\";\nconst successCallBack = (success) => {\n  toast.error(success.data.message);\n};\n\nconst errorCallBack = (error) => {\n  const expectedError =\n    error.response &&\n    error.response.status >= 404 &&\n    error.response.status < 500;\n  if (!expectedError) {\n    console.log(\"logging the error\", error);\n    toast.error(\"an unexpected error occured\");\n  }\n  return Promise.reject(error);\n};\n\n//intercept errors while communicating with backend server\naxios.interceptors.response.use(successCallBack, errorCallBack);\n\nexport default {\n  get: axios.get,\n  post: axios.post,\n  put: axios.put,\n  delete: axios.delete,\n};\n"]},"metadata":{},"sourceType":"module"}