{"ast":null,"code":"import axios from \"axios\";\nimport { toast } from \"react-toastify\"; //intercept errors while communicating with backend server\n\naxios.interceptors.response.use(successCallBack, errorCallBack);\n\nsuccessCallBack = success => {\n  console.log(success);\n};\n\nerrorCallBack = error => {\n  const expectedError = error.response && error.response.status >= 404 && error.response.status < 500;\n\n  if (!expectedError) {\n    console.log(\"logging the error\", error);\n    toast.error(\"an unexpected error occured\");\n  }\n\n  return Promise.reject(error);\n};\n\nexport default {\n  get: axios.get,\n  post: axios.post,\n  put: axios.put,\n  delete: axios.delete\n};","map":{"version":3,"sources":["/Users/prashantkansal/Desktop/techgropse/digiTender/digiTenderFrontend/src/services/httpService.js"],"names":["axios","toast","interceptors","response","use","successCallBack","errorCallBack","success","console","log","error","expectedError","status","Promise","reject","get","post","put","delete"],"mappings":"AAAA,OAAOA,KAAP,MAAkB,OAAlB;AACA,SAASC,KAAT,QAAsB,gBAAtB,C,CAEA;;AACAD,KAAK,CAACE,YAAN,CAAmBC,QAAnB,CAA4BC,GAA5B,CAAgCC,eAAhC,EAAiDC,aAAjD;;AAEAD,eAAe,GAAIE,OAAD,IAAa;AAC7BC,EAAAA,OAAO,CAACC,GAAR,CAAYF,OAAZ;AACD,CAFD;;AAIAD,aAAa,GAAII,KAAD,IAAW;AACzB,QAAMC,aAAa,GACjBD,KAAK,CAACP,QAAN,IACAO,KAAK,CAACP,QAAN,CAAeS,MAAf,IAAyB,GADzB,IAEAF,KAAK,CAACP,QAAN,CAAeS,MAAf,GAAwB,GAH1B;;AAIA,MAAI,CAACD,aAAL,EAAoB;AAClBH,IAAAA,OAAO,CAACC,GAAR,CAAY,mBAAZ,EAAiCC,KAAjC;AACAT,IAAAA,KAAK,CAACS,KAAN,CAAY,6BAAZ;AACD;;AACD,SAAOG,OAAO,CAACC,MAAR,CAAeJ,KAAf,CAAP;AACD,CAVD;;AAYA,eAAe;AACbK,EAAAA,GAAG,EAAEf,KAAK,CAACe,GADE;AAEbC,EAAAA,IAAI,EAAEhB,KAAK,CAACgB,IAFC;AAGbC,EAAAA,GAAG,EAAEjB,KAAK,CAACiB,GAHE;AAIbC,EAAAA,MAAM,EAAElB,KAAK,CAACkB;AAJD,CAAf","sourcesContent":["import axios from \"axios\";\nimport { toast } from \"react-toastify\";\n\n//intercept errors while communicating with backend server\naxios.interceptors.response.use(successCallBack, errorCallBack);\n\nsuccessCallBack = (success) => {\n  console.log(success);\n};\n\nerrorCallBack = (error) => {\n  const expectedError =\n    error.response &&\n    error.response.status >= 404 &&\n    error.response.status < 500;\n  if (!expectedError) {\n    console.log(\"logging the error\", error);\n    toast.error(\"an unexpected error occured\");\n  }\n  return Promise.reject(error);\n};\n\nexport default {\n  get: axios.get,\n  post: axios.post,\n  put: axios.put,\n  delete: axios.delete,\n};\n"]},"metadata":{},"sourceType":"module"}